version: '3'
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zxcv
      POSTGRES_DB: student_service_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend-student-service:
    image: ramit07/springboot_studentservice
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    expose:
      - 8090
    environment:
      db_url: jdbc:postgresql://postgres-db:5432/student_service_db
      db_username: postgres
      db_password: zxcv
    depends_on:
      postgres-db:
        condition: service_started
    restart: always

  api-gateway:
    image: ubuntu/nginx
    volumes:
      - ./src/main/resources/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
        - 8085:80
    depends_on:
      backend-student-service:
        condition: service_started
    restart: always

#Creating volume for data to persist even when postgres container is stopped or removed
volumes:
  pgdata: